### ISSUE TITLE
Always have the tools up to date.

### ISSUE THREAD

**Issue by ravenfeld** [inovex/gitlab-ci-android#14]
I think it is possible with this command to have the latest tools all the time.

I am in 31 and I can't use your docker anymore, it's a shame.    

- CMDLINE_TOOLS_VERSION="$(curl https://developer.android.com/studio/index.html#command-tools | sed -n 's/.*commandlinetools-linux-\(.*\)_latest.zip.*/\1/p' | uniq)"

**Comment by chrjsorg** [comment]
Done in version 21. Thanks.
