### ISSUE TITLE
Adding new JDK version

### ISSUE THREAD

**Issue by AurelienOkeenea** [inovex/gitlab-ci-android#20]
Hello,
My team and I are using your Docker image for our CI in our Android app project.
As the most recent version of Android Studio (Android Studio Ladybug) recommends using Java 21 as the JDK version, we would like to know if it was possible for you to add that JDK 21 in your Docker image ?
Thank you very much !

**Comment by chrjsorg** [comment]
Enjoy! :)

https://github.com/inovex/gitlab-ci-android/pull/21
